Public Enum PostProcessPreferences As Integer
    ODP_VOUCHER_NUM
    ODP_ENTITY
    ODP_BANK_ACCOUNT
    ODP_DOCUMENT_NUM
    ODP_PAYMENT_DATE
    ODP_PAYMENT_AMOUNT
    ODP_CURR
    ODP_STATUS
    ODP_STATUS_DATE
    ODP_SUPPLIER
    ODP_RATE_TYPE
    ODP_RATE_DATE
    ODP_PAYMENT_RATE
    ODP_DOCTYPE_ID
    ODP_DOC_I_BATCH
    REMITOS_NRO_REMITO
    REMITOS_NRO_ORDEN
    REMITOS_DOCTYPE_ID
    REMITOS_NRO_LOTE
    RULE_ID
    COMMONINDEX_ID
    DOCTYPEID1
    DOCTYPEID2
End Enum