Public Enum CacheType
    Archivos
    DocTypes
    Forms
    Groups
    Indexs
    Other
    Outlook
    Results
    Search
    Users
    UsersRights
    Volume
    Workflow
    AllObjects
End Enum

Public Enum CacheSubType
    Asociations
    AutocompleteKeys
    DocType
    DocTypes
    DsDocTypes
    DocTypeByGroup
    DocTypeName
    DocTypeUserRightFromArchive
    FileContainsText
    FullName
    GetAditional
    IndexsArray
    IndexsArrayHierachical
    IndexsDT
    IndexsIdsByDocTypeId
    IndexsName
    IndexRightValues
    IndexsProperties
    IndexsSchemaOfDT
    IndexValues
    Name
    NewResult
    NewNewResult
    Result
    ShowAndEditForms
    SpecificIndexsRights
    StepStates
    SustIndex
    UserGroups
    UserRights
    UserRight
    VolumeListId
    VolumesDs
    WebQuerySearch
    WFDocTypes
    WFRulesOpt
    WFSteps
    '///////////////////
    'Se agregaron estos enumeradores para reemplazar los hashtables
    WFRulesByStepID
    WFRulesByRuleID
    WFStepsOpt
    WFStepsColors
    WFStepsState
    WFStepId
    DocTypesAsWFbyStepId
    RestrictionsStrings
    RestrictionsIndexs
    Modules
    CurrentTask
    CurrentTasks
    CommonFunctions
    TasksVariables
    '//////////////////
End Enum