<%@ Page Language="C#" AutoEventWireup="true" CodeFile="ReportsViewer.aspx.cs" Inherits="ReportsViewer" Title="Zamba WorkFlow Informes" MasterPageFile="~/ZambaMaster.master" EnableEventValidation="false" %>

<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="ajaxToolKit" %>
<%@ Register TagPrefix="MyUC" TagName="TaskCount" Src="~/WfReports/UserControls/UCAsignedTasksCount/UCAsignedTasksCount.ascx" %>
<%@ Register TagPrefix="MyUC" TagName="AverageTime" Src="~/WfReports/UserControls/UCAverageTimeInSteps/UCAverageTimeInSteps.ascx" %>
<%@ Register TagPrefix="MyUC" TagName="TaskBalances" Src="~/WfReports/UserControls/UCTaskBalances/UCTaskBalances.ascx" %>
<%@ Register TagPrefix="MyUC" TagName="TaskExpire" Src="~/WfReports/UserControls/UCTaskToExpire/UCTaskToExpire.ascx" %>
<%@ Register TagPrefix="MyUC" TagName="GenericReport" Src="~/WfReports/UserControls/UCGenericReport/UcGenericReport.ascx" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
    <%--  <asp:UpdatePanel ID="UpdatePanel1" runat="server" UpdateMode="Conditional">
        <ContentTemplate>--%>
    <div style="margin: 0px 0px 0px 0px">
        <table cellpadding="0" cellspacing="0" class="ms-formbody">
            <tr style="margin: 0px 0px 0px 0px">
                <td valign="top" style="width: 2px" class="ms-tabinactive">
                </td>
                <td valign="top" style="margin: 0px 0px 0px 0px" bgcolor="#F2F8FF" class="ms-topnav">
                    <asp:TreeView ID="TreeView1" runat="server" NodeIndent="1" ShowCheckBoxes="Leaf" Width="250px" ShowExpandCollapse="False" NodeWrap="False" OnSelectedNodeChanged="TreeView1_SelectedNodeChanged" ShowLines="False" NodeStyle-NodeSpacing="0" NodeStyle-HorizontalPadding="0" NodeStyle-ChildNodesPadding="0" NodeStyle-VerticalPadding="0" ParentNodeStyle-HorizontalPadding="0" ParentNodeStyle-NodeSpacing="0" ParentNodeStyle-VerticalPadding="0" RootNodeStyle-ChildNodesPadding="0" RootNodeStyle-HorizontalPadding="0" RootNodeStyle-NodeSpacing="0" RootNodeStyle-VerticalPadding="0" SelectedNodeStyle-ChildNodesPadding="0" SelectedNodeStyle-HorizontalPadding="0" SelectedNodeStyle-NodeSpacing="0" SelectedNodeStyle-VerticalPadding="0" NodeStyle-Width="200" ParentNodeStyle-Width="200" SelectedNodeStyle-Width="200" LeafNodeStyle-Width="200" HoverNodeStyle-Width="200" AutoGenerateDataBindings="False" PopulateNodesFromClient="False" EnableClientScript="False" OnTreeNodeCheckChanged="TreeView1_TreeNodeCheckChanged">
                        <ParentNodeStyle Font-Bold="False" />
                        <HoverNodeStyle Font-Underline="True" ForeColor="#6666AA" Font-Size="X-Small" />
                        <SelectedNodeStyle BackColor="#B5B5B5" Font-Underline="False" HorizontalPadding="0px" VerticalPadding="0px" />
                        <RootNodeStyle ChildNodesPadding="0px" HorizontalPadding="0px" NodeSpacing="0px" VerticalPadding="0px" />
                        <NodeStyle Font-Names="Tahoma" Font-Size="8pt" ForeColor="Black" HorizontalPadding="0px" NodeSpacing="0px" VerticalPadding="2px" />
                        <LeafNodeStyle Font-Size="XX-Small" />
                    </asp:TreeView>
                    <br />
                    <div>
                        <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="Aplicar selección" Width="123px" BackColor="#315F9B" ForeColor="White" />&nbsp;</div>
                    <div>
                        <asp:Button ID="btnRefresh" runat="server" OnClick="btnRefresh_Click" Text="Actualizar" Width="123px" BackColor="#315F9B" ForeColor="White" />&nbsp;</div>
                </td>
                <td valign="top" style="margin: 0px 0px 0px 0px" class="ms-tabinactive">
                    <asp:Table runat="server" ID="tblUcs" CellPadding="0" CellSpacing="0" CssClass="ms-tabinactive" BackColor="#9CC1F5">
                        <asp:TableRow>
                            <asp:TableCell VerticalAlign="top" Height="50px" ID="td1" RowSpan="0">
                                <asp:UpdatePanel runat="server" ID="upTaskCount">
                                    <ContentTemplate>
                                        <MyUC:TaskCount ID="ucTaskCount" runat="server" />
                                    </ContentTemplate>
                                </asp:UpdatePanel>
                                </asp:TableCell>
                                <asp:TableCell VerticalAlign="top" Height="50px" ID="TableCell1" RowSpan="0">
                                    <asp:UpdatePanel runat="server" ID="upExpire">
                                        <ContentTemplate>
                                            <MyUC:TaskExpire ID="ucTaskExpire" runat="server" />
                                        </ContentTemplate>
                                    </asp:UpdatePanel>
                            </asp:TableCell>
                        </asp:TableRow>
                        <asp:TableRow>
                            <asp:TableCell VerticalAlign="top" Height="50px" ID="td3">
                                <asp:UpdatePanel runat="server" ID="upAverageTime">
                                    <ContentTemplate>
                                        <MyUC:AverageTime ID="ucAverageTime" runat="server" />
                                    </ContentTemplate>
                                </asp:UpdatePanel>
                            </asp:TableCell>
                            <asp:TableCell VerticalAlign="top" Height="50px" ID="TableCell2" RowSpan="0">
                                <asp:UpdatePanel runat="server" ID="upTaskBalance">
                                    <ContentTemplate>
                                        <MyUC:TaskBalances ID="ucTaskBalance" runat="server" />
                                    </ContentTemplate>
                                </asp:UpdatePanel>
                            </asp:TableCell>
                        </asp:TableRow>
                        <asp:TableRow>
                            <asp:TableCell>
                                <asp:UpdatePanel ID="upGenericReport" runat="server" UpdateMode="Conditional">
                                    <ContentTemplate>
                                        <div runat="server" id="divGenericos">
                                            <asp:Repeater ID="rpGeneric" runat="server">
                                                <ItemTemplate>
                                                    <MyUC:GenericReport ID="UcGenericReport" runat="server" Query='<%# DataBinder.Eval(Container.DataItem, "Query") %>' Title='<%# DataBinder.Eval(Container.DataItem, "QueryName") %>' />
                                                </ItemTemplate>
                                            </asp:Repeater>
                                        </div>
                                    </ContentTemplate>
                                </asp:UpdatePanel>
                            </asp:TableCell>
                        </asp:TableRow>
                    </asp:Table>
                </td>
            </tr>
        </table>
    </div>
    <%-- </ContentTemplate>
    </asp:UpdatePanel>--%>
</asp:Content>
