Imports Zamba.Core
Imports Zamba.Servers
Imports Zamba.Data
Imports Zamba.Servers.Server
Imports Zamba.Core.ZClass
Imports System.Text
Imports System.Collections.Generic

Public Class SectionDiagramFactory

    Public Function GetSectionAndEntities() As DataSet

        'Dim Query As String = "SELECT DOC_TYPE_GROUP.DOC_TYPE_GROUP_NAME AS SectionName, DOC_TYPE_GROUP.DOC_TYPE_GROUP_ID AS SectionId, DOC_TYPE_GROUP.ICON AS SectionIconId, DOC_TYPE_GROUP.OBJECT_TYPE_ID AS SectionObjectTypeId, DOC_TYPE.DOC_TYPE_ID AS EntityId, DOC_TYPE.DOC_TYPE_NAME AS EntityName, DOC_TYPE.ICON_ID AS EntityIconId, DOC_TYPE.OBJECT_TYPE_ID AS EntityObjectTypeId, DOC_TYPE_GROUP.PARENT_ID AS SectionParentId FROM         DOC_TYPE INNER JOIN DOC_TYPE_R_DOC_TYPE_GROUP ON DOC_TYPE.DOC_TYPE_ID = DOC_TYPE_R_DOC_TYPE_GROUP.DOC_TYPE_ID INNER JOIN DOC_TYPE_GROUP ON DOC_TYPE_R_DOC_TYPE_GROUP.DOC_TYPE_GROUP = DOC_TYPE_GROUP.DOC_TYPE_GROUP_ID INNER JOIN USR_RIGHTS AS USR_RIGHTS_1 ON DOC_TYPE.DOC_TYPE_ID = USR_RIGHTS_1.ADITIONAL INNER JOIN USR_RIGHTS ON DOC_TYPE_GROUP.DOC_TYPE_GROUP_ID = USR_RIGHTS.ADITIONAL WHERE     (USR_RIGHTS.RTYPE = 1) AND (USR_RIGHTS_1.RTYPE = 1) AND (USR_RIGHTS_1.OBJID = 2) AND (USR_RIGHTS.OBJID = 3)"

        Dim Query As String = "SELECT Distinct DOC_TYPE_GROUP.DOC_TYPE_GROUP_NAME AS SectionName, DOC_TYPE_GROUP.DOC_TYPE_GROUP_ID AS SectionId, DOC_TYPE_GROUP.ICON AS SectionIconId, DOC_TYPE_GROUP.OBJECT_TYPE_ID AS SectionObjectTypeId, DOC_TYPE.DOC_TYPE_ID AS EntityId, DOC_TYPE.DOC_TYPE_NAME AS EntityName, DOC_TYPE.ICON_ID AS EntityIconId, DOC_TYPE.OBJECT_TYPE_ID AS EntityObjectTypeId, DOC_TYPE_GROUP.PARENT_ID AS SectionParentId FROM         DOC_TYPE INNER JOIN DOC_TYPE_R_DOC_TYPE_GROUP ON DOC_TYPE.DOC_TYPE_ID = DOC_TYPE_R_DOC_TYPE_GROUP.DOC_TYPE_ID INNER JOIN DOC_TYPE_GROUP ON DOC_TYPE_R_DOC_TYPE_GROUP.DOC_TYPE_GROUP = DOC_TYPE_GROUP.DOC_TYPE_GROUP_ID INNER JOIN USR_RIGHTS AS USR_RIGHTS_1 ON DOC_TYPE.DOC_TYPE_ID = USR_RIGHTS_1.ADITIONAL INNER JOIN USR_RIGHTS ON DOC_TYPE_GROUP.DOC_TYPE_GROUP_ID = USR_RIGHTS.ADITIONAL WHERE     (USR_RIGHTS.RTYPE = 1) AND (USR_RIGHTS_1.RTYPE = 1) AND (USR_RIGHTS_1.OBJID = 2) AND (USR_RIGHTS.OBJID = 3) ORDER BY SectionId"

        Dim ds As DataSet = Server.Con.ExecuteDataset(CommandType.Text, Query)
        Return ds

    End Function
End Class
