Public Enum EnumPaquetes As Integer
    PAQ_CreateTable_DOC_TYPE_R_DOC_TYPE
    PAQ_CreateTable_Foro
    PAQ_CreateTable_PreProcessIDs
    PAQ_CreateTable_PRO
    PAQ_CreateTable_ReportBuilder
    PAQ_CreateTable_REPORTE_ID
    PAQ_CreateTable_Schedule
    PAQ_CreateTable_USRNOTES
    PAQ_CreateTable_ZBarCode
    PAQ_CreateTable_ZBarcodeComplete
    PAQ_CreateTable_Zext_ZFrms
    PAQ_CreateTable_ZNetronShapes
    PAQ_CreateTable_Zopt
    PAQ_CreateTable_ZQSENTENCE
    PAQ_CreateTable_ZServidores
    PAQ_CreateTable_ZServidores2
    PAQ_CreateTable_ZTempL
    PAQ_CreateTables_ABN
    PAQ_CreateTables_Export
    PAQ_CreateTables_Exportacion_Mails
    PAQ_CreateTables_IndexLink
    PAQ_CreateTable_WFInsert
    PAQ_CreateTable_WFStep
    PAQ_CreateTable_WFStepHst
    PAQ_CreateTable_WorkFlow
    PAQ_CreateTables_WF_SQLServer
    PAQ_CreateTables_Mensajes
    PAQ_CreateTable_ZMailConfig
    PAQ_CreateTables_Versiones
    PAQ_AddColumn_DOC_I_Fecha
    PAQ_AddColumn_Doc_Type_MB
    PAQ_AddColumn_DOCT_Filesize
    PAQ_AddColumn_INDEX_R_DOC_TYPE_Complete
    PAQ_AddColumn_ip_type_IP_CHECKBATCH
    PAQ_AddColumn_Z_GroupToNotify_GroupID
    PAQ_AddColumn_ZEXPORTCONTROL_Doc_Type_Id
    PAQ_AddColumn_Zqueryname_querytype
    PAQ_AddColumn_ZsecOption_RepeatPassword
    PAQ_AddColumns_DOC_T
    PAQ_AddColumns_INDEX_R_DOC_TYPE
    PAQ_AddColumns_TABLATEMP
    PAQ_DeleteColumn_ILST_ITEMID
    PAQ_AlterTable_DOC_I
    PAQ_AlterTable_DOC_T
    PAQ_AlterTable_INDEX_R_DOC_TYPE
    PAQ_AlterTable_IP_FOLDER
    PAQ_AlterTable_MESSAGE
    PAQ_AlterTable_MSG_ATTACH
    PAQ_AlterTable_USRNOTES
    PAQ_AlterTable_Usrtable
    PAQ_AlterTable_Usrtable_Correo
    PAQ_AlterTable_Usrtable_NameIndex
    PAQ_AlterTable_Usrtable_usrtable_index
    PAQ_AlterTable_WF_DT
    PAQ_AlterTable_WFStep
    PAQ_AlterTable_WFStepStates
    PAQ_AlterTable_ZbarCode
    PAQ_AlterTable_ZBarcodeComplete
    PAQ_AlterTable_ZexportControl
    PAQ_AlterTable_ZForum
    PAQ_AlterTables_DOC_T
    PAQ_AlterTables_ZQColumns_ZQKeys
    PAQ_AlterColumn_User_hst_Action_Date
    PAQ_CreateView_ZviewShowInsertsHistory
    PAQ_CreateView_Zvw_LoginsFailed_100
    PAQ_CreateView_Zvw_WFHistory_200
    PAQ_CreateView_ZVW_WFHISTORYCI_200
    PAQ_CreateView_ZWFViewReport
    PAQ_CreateViews_DOC
    PAQ_CreateViews_General2
    PAQ_CreateStore_GET_MY_MESSAGES_PKG
    PAQ_CreateStore_sp_GetLogInformation
    PAQ_CreateStore_zsp_doctypes_200
    PAQ_CreateStore_Zsp_Imports_100
    PAQ_CreateStore_zsp_messages_100_GetMyMessagesNew
    PAQ_CreateStore_zsp_objects_100
    PAQ_CreateStore_ZSP_SECURITY_100
    PAQ_CreateStore_Zsp_users_200
    PAQ_CreateStore_ZSP_VERSION_300
    PAQ_CreateStore_Zsp_Workflow_100
    PAQ_CreateStore_ZSP_ZBARCODE_200_PKG
    PAQ_CreateStore_zspimportsGetProcessHistory
    PAQ_CreateStore_Zvw_Reportecaratulas
    PAQ_CreateStores_ABN
    PAQ_CreateStores_General
    PAQ_CreateStores_WorkFlow
    PAQ_CreateStores_WorkFlow2
    PAQ_RunScripts
    PAQ_AlterTable_WFStepHst
    PAQ_CreateTable_ZTaskStatus
    PAQ_CreateTable_ZIR
    PAQ_PRUEBADIEGO
End Enum