//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zamba.AgentBusiness.AgentServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AgentServiceReference.IAgentService")]
    public interface IAgentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgentService/SaveUCMCount", ReplyAction="http://tempuri.org/IAgentService/SaveUCMCountResponse")]
        void SaveUCMCount(string Client, string LicenceType, long Count, System.DateTime CountDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgentService/SaveUCMDataSet", ReplyAction="http://tempuri.org/IAgentService/SaveUCMDataSetResponse")]
        string SaveUCMDataSet(System.Data.DataSet UCMDS, string Client, System.DateTime DsDate, string Server, string DataBase);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgentService/SaveILMDataSet", ReplyAction="http://tempuri.org/IAgentService/SaveILMDataSetResponse")]
        string SaveILMDataSet(System.Data.DataSet UCMDS, string Client, System.DateTime DsDate, string Server, string DataBase);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAgentServiceChannel : Zamba.AgentBusiness.AgentServiceReference.IAgentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AgentServiceClient : System.ServiceModel.ClientBase<Zamba.AgentBusiness.AgentServiceReference.IAgentService>, Zamba.AgentBusiness.AgentServiceReference.IAgentService {
        
        public AgentServiceClient() {
        }
        
        public AgentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AgentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SaveUCMCount(string Client, string LicenceType, long Count, System.DateTime CountDate) {
            base.Channel.SaveUCMCount(Client, LicenceType, Count, CountDate);
        }
        
        public string SaveUCMDataSet(System.Data.DataSet UCMDS, string Client, System.DateTime DsDate, string Server, string DataBase) {
            return base.Channel.SaveUCMDataSet(UCMDS, Client, DsDate, Server, DataBase);
        }
        
        public string SaveILMDataSet(System.Data.DataSet UCMDS, string Client, System.DateTime DsDate, string Server, string DataBase) {
            return base.Channel.SaveILMDataSet(UCMDS, Client, DsDate, Server, DataBase);
        }
    }
}
