<%@ Page Language="C#" AutoEventWireup="true" CodeFile="ReportsViewer.aspx.cs" Inherits="ReportsViewer"
    Title="Zamba WorkFlow Informes" MasterPageFile="~/ZambaMaster.master" EnableEventValidation="false" %>

<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="ajaxToolKit" %>
<%@ Register TagPrefix="MyUC" TagName="TaskCount" Src="~/WfReports/WFReportesv1.1/UserControls/UCAsignedTasksCount/UCAsignedTasksCount.ascx" %>
<%@ Register TagPrefix="MyUC" TagName="AverageTime" Src="~/WfReports/WFReportesv1.1/UserControls/UCAverageTimeInSteps/UCAverageTimeInSteps.ascx" %>
<%@ Register TagPrefix="MyUC" TagName="TaskBalances" Src="~/WfReports/WFReportesv1.1/UserControls/UCTaskBalances/UCTaskBalances.ascx" %>
<%@ Register TagPrefix="MyUC" TagName="TaskExpire" Src="~/WfReports/WFReportesv1.1/UserControls/UCTaskToExpire/UCTaskToExpire.ascx" %>
<%@ Register TagPrefix="MyUC" TagName="GenericReport" Src="~/WfReports/WFReportesv1.1/UserControls/UCGenericReport/UcGenericReport.ascx" %>
<%@ Register TagPrefix="MyUC" TagName="DynamicReport" Src="~/WfReports/WFReportesv1.1/UserControls/UCDynamicReport/UCDynamicReport.ascx" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
    <div style="margin: 0px 0px 0px 0px">
        <table cellpadding="0" cellspacing="0" class="ms-formbody">
            <tr style="margin: 0px 0px 0px 0px">
                
                <%--<asp:UpdatePanel ID="UpdatePanel1" runat="server" UpdateMode="Conditional">--%>
                    <%--<ContentTemplate>--%>
                        <td valign="top" style="margin: 0px 0px 0px 0px" bgcolor="#F2F8FF" class="ms-topnav">
                             <asp:TreeView ID="TreeView1" runat="server" ShowCheckBoxes="Leaf"
                        Width="250px" OnSelectedNodeChanged="TreeView1_SelectedNodeChanged" 
                        NodeStyle-NodeSpacing="0" NodeStyle-HorizontalPadding="0" NodeStyle-ChildNodesPadding="0"
                        NodeStyle-VerticalPadding="0" ParentNodeStyle-HorizontalPadding="0" ParentNodeStyle-NodeSpacing="0"
                        ParentNodeStyle-VerticalPadding="0" RootNodeStyle-ChildNodesPadding="0" RootNodeStyle-HorizontalPadding="0"
                        RootNodeStyle-NodeSpacing="0" RootNodeStyle-VerticalPadding="0" SelectedNodeStyle-ChildNodesPadding="0"
                        SelectedNodeStyle-HorizontalPadding="0" SelectedNodeStyle-NodeSpacing="0" SelectedNodeStyle-VerticalPadding="0"
                        NodeStyle-Width="200" ParentNodeStyle-Width="200" SelectedNodeStyle-Width="200"
                        LeafNodeStyle-Width="200" HoverNodeStyle-Width="200" AutoGenerateDataBindings="False"
                        PopulateNodesFromClient="False" EnableClientScript="False" 
                        OnTreeNodeCheckChanged="TreeView1_TreeNodeCheckChanged" ShowExpandCollapse="False" 
                                 onload="TreeView1_Load" Font-Size="Smaller">
                        <ParentNodeStyle Font-Bold="True" Font-Size="X-Small" ForeColor="Black" />
                        <HoverNodeStyle Font-Size="X-Small" />
                        <SelectedNodeStyle HorizontalPadding="0px" VerticalPadding="0px" />
                        <RootNodeStyle ChildNodesPadding="0px" HorizontalPadding="0px" NodeSpacing="0px"
                            VerticalPadding="0px" Font-Bold="True" Font-Size="Small" ForeColor="Black" />
                        <NodeStyle HorizontalPadding="0px" NodeSpacing="0px" VerticalPadding="0px" />
                        <LeafNodeStyle Font-Size="X-Small" />
                    </asp:TreeView>
                            <br />
                            <div>
                                <asp:Button ID="btnImplementSelection" runat="server" OnClick="btnImplementSelection_Click" Text="Aplicar selección"
                                    Width="123px" BackColor="#315F9B" ForeColor="White" />&nbsp;</div>
                            <div>
                                &nbsp;</div>
                                    
                            <div>
                                <asp:Button ID="btnInvisibleButton" runat="server" Text="Botón Invisible"
                                    Width="123px" BackColor="#315F9B" ForeColor="White" />&nbsp;</div>
                                    
                            <ajaxToolkit:ModalPopupExtender ID="PopUpUltimate" runat="server"
                                                            TargetControlID="btnInvisibleButton"
                                                            PopupControlID="PopupPanel"
                                                            CacheDynamicResults="true"
                            />
        
                            <asp:Panel ID="PopupPanel" runat="server" 
                            Style="display: none" 
                            BackColor="#FF6699"
                            Width="191px">
                            
                            <asp:Label runat="server" Id="lblDynamicReportName" Text="" Font-Bold="true" Font-Size="Medium" >
                            </asp:Label>
    
                            <asp:DataList runat="server" ID="ListaIndices" EnableViewState="true">
                            <ItemTemplate>
                            <asp:Label runat="server" Id="IndexName" Text='<%# DataBinder.Eval(Container.DataItem, "IndexName") %>'>
                            </asp:Label> 
                            <asp:Label runat="server" Id="IndexOperator" Text='<%# DataBinder.Eval(Container.DataItem, "IndexOperator") %>'>
                            </asp:Label> 
                            <asp:TextBox runat="server" Id="IndexData" Text='<%# DataBinder.Eval(Container.DataItem, "IndexData") %>' >
                            </asp:TextBox>
                            </ItemTemplate>
                            </asp:DataList>
                                <asp:Button ID="btnAccept" runat="server" Text="Aceptar" OnClick="btnAccept_click"/>
                                <asp:Button ID="btnCancel" runat="server" Text="Cancelar" OnClick="btnCancel_click" />
                            </asp:Panel>
                            
                        </td>
                   <%-- </ContentTemplate>
                </asp:UpdatePanel>--%>
                
                <td valign="top" style="margin: 0px 0px 0px 0px; width:100%" class="ms-tabinactive">

                    <asp:Label ID="Label1" runat="server"></asp:Label>

                    <asp:Table runat="server" ID="tblUcs" CellPadding="0" CellSpacing="0" CssClass="ms-tabinactive"
                               BackColor="#9CC1F5" >
                                   
                        <asp:TableRow>
                            <asp:TableCell VerticalAlign="top" Height="50px" ID="td1" RowSpan="0">
                                <MyUC:TaskCount ID="ucTaskCount" runat="server" />
                            </asp:TableCell>
                                
                            <asp:TableCell VerticalAlign="top" Height="50px" ID="TableCell1" RowSpan="0">
                                <MyUC:TaskExpire ID="ucTaskExpire" runat="server" />
                            </asp:TableCell>
                        </asp:TableRow>
                        
                        <asp:TableRow>
                            <asp:TableCell VerticalAlign="top" Height="50px" ID="td3">
                                <MyUC:AverageTime ID="ucAverageTime" runat="server" />
                            </asp:TableCell>
                            <asp:TableCell VerticalAlign="top" Height="50px" ID="TableCell2" RowSpan="0">
                                <MyUC:TaskBalances ID="ucTaskBalance" runat="server" />
                            </asp:TableCell>
                        </asp:TableRow>
                            
                    </asp:Table>
                            
                </td>
                
            </tr>
        </table>
    </div>
</asp:Content>
