//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvocacionServWDigDepFiel.wDigDepFiel {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Autenticacion", Namespace="ar.gov.afip.dia.serviciosWeb.wDigDepFiel")]
    [System.SerializableAttribute()]
    public partial class Autenticacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CuitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoAgenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RolField;
        
        private string TokenField;
        
        private string SignField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Cuit {
            get {
                return this.CuitField;
            }
            set {
                if ((object.ReferenceEquals(this.CuitField, value) != true)) {
                    this.CuitField = value;
                    this.RaisePropertyChanged("Cuit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TipoAgente {
            get {
                return this.TipoAgenteField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoAgenteField, value) != true)) {
                    this.TipoAgenteField = value;
                    this.RaisePropertyChanged("TipoAgente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Rol {
            get {
                return this.RolField;
            }
            set {
                if ((object.ReferenceEquals(this.RolField, value) != true)) {
                    this.RolField = value;
                    this.RaisePropertyChanged("Rol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public string Sign {
            get {
                return this.SignField;
            }
            set {
                if ((object.ReferenceEquals(this.SignField, value) != true)) {
                    this.SignField = value;
                    this.RaisePropertyChanged("Sign");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Recibo", Namespace="ar.gov.afip.dia.serviciosWeb.wDigDepFiel")]
    [System.SerializableAttribute()]
    public partial class Recibo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int codErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int codError {
            get {
                return this.codErrorField;
            }
            set {
                if ((this.codErrorField.Equals(value) != true)) {
                    this.codErrorField = value;
                    this.RaisePropertyChanged("codError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string descError {
            get {
                return this.descErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.descErrorField, value) != true)) {
                    this.descErrorField = value;
                    this.RaisePropertyChanged("descError");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Familia", Namespace="ar.gov.afip.dia.serviciosWeb.wDigDepFiel")]
    [System.SerializableAttribute()]
    public partial class Familia : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoField;
        
        private int cantidadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoField, value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int cantidad {
            get {
                return this.cantidadField;
            }
            set {
                if ((this.cantidadField.Equals(value) != true)) {
                    this.cantidadField = value;
                    this.RaisePropertyChanged("cantidad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WsDummyResponse", Namespace="ar.gov.afip.dia.serviciosWeb.wDigDepFiel")]
    [System.SerializableAttribute()]
    public partial class WsDummyResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string appserverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dbserverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string authserverField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string appserver {
            get {
                return this.appserverField;
            }
            set {
                if ((object.ReferenceEquals(this.appserverField, value) != true)) {
                    this.appserverField = value;
                    this.RaisePropertyChanged("appserver");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string dbserver {
            get {
                return this.dbserverField;
            }
            set {
                if ((object.ReferenceEquals(this.dbserverField, value) != true)) {
                    this.dbserverField = value;
                    this.RaisePropertyChanged("dbserver");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string authserver {
            get {
                return this.authserverField;
            }
            set {
                if ((object.ReferenceEquals(this.authserverField, value) != true)) {
                    this.authserverField = value;
                    this.RaisePropertyChanged("authserver");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="ar.gov.afip.dia.serviciosWeb.wDigDepFiel", ConfigurationName="wDigDepFiel.wDigDepFielSoap")]
    public interface wDigDepFielSoap {
        
        // CODEGEN: Generating message contract since element name autentica from namespace ar.gov.afip.dia.serviciosWeb.wDigDepFiel is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="ar.gov.afip.dia.serviciosWeb.wDigDepFiel/AvisoRecepAcept", ReplyAction="*")]
        InvocacionServWDigDepFiel.wDigDepFiel.AvisoRecepAceptResponse AvisoRecepAcept(InvocacionServWDigDepFiel.wDigDepFiel.AvisoRecepAceptRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="ar.gov.afip.dia.serviciosWeb.wDigDepFiel/AvisoRecepAcept", ReplyAction="*")]
        System.Threading.Tasks.Task<InvocacionServWDigDepFiel.wDigDepFiel.AvisoRecepAceptResponse> AvisoRecepAceptAsync(InvocacionServWDigDepFiel.wDigDepFiel.AvisoRecepAceptRequest request);
        
        // CODEGEN: Generating message contract since element name autentica from namespace ar.gov.afip.dia.serviciosWeb.wDigDepFiel is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="ar.gov.afip.dia.serviciosWeb.wDigDepFiel/AvisoDigit", ReplyAction="*")]
        InvocacionServWDigDepFiel.wDigDepFiel.AvisoDigitResponse AvisoDigit(InvocacionServWDigDepFiel.wDigDepFiel.AvisoDigitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="ar.gov.afip.dia.serviciosWeb.wDigDepFiel/AvisoDigit", ReplyAction="*")]
        System.Threading.Tasks.Task<InvocacionServWDigDepFiel.wDigDepFiel.AvisoDigitResponse> AvisoDigitAsync(InvocacionServWDigDepFiel.wDigDepFiel.AvisoDigitRequest request);
        
        // CODEGEN: Generating message contract since element name DummyResult from namespace ar.gov.afip.dia.serviciosWeb.wDigDepFiel is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="ar.gov.afip.dia.serviciosWeb.wDigDepFiel/Dummy", ReplyAction="*")]
        InvocacionServWDigDepFiel.wDigDepFiel.DummyResponse Dummy(InvocacionServWDigDepFiel.wDigDepFiel.DummyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="ar.gov.afip.dia.serviciosWeb.wDigDepFiel/Dummy", ReplyAction="*")]
        System.Threading.Tasks.Task<InvocacionServWDigDepFiel.wDigDepFiel.DummyResponse> DummyAsync(InvocacionServWDigDepFiel.wDigDepFiel.DummyRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AvisoRecepAceptRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AvisoRecepAcept", Namespace="ar.gov.afip.dia.serviciosWeb.wDigDepFiel", Order=0)]
        public InvocacionServWDigDepFiel.wDigDepFiel.AvisoRecepAceptRequestBody Body;
        
        public AvisoRecepAceptRequest() {
        }
        
        public AvisoRecepAceptRequest(InvocacionServWDigDepFiel.wDigDepFiel.AvisoRecepAceptRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="ar.gov.afip.dia.serviciosWeb.wDigDepFiel")]
    public partial class AvisoRecepAceptRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public InvocacionServWDigDepFiel.wDigDepFiel.Autenticacion autentica;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nroLegajo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cuitDeclarante;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string cuitPSAD;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string cuitIE;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string codigo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.DateTime fechaHoraAcept;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ticket;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string sigea;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string nroGuia;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public System.DateTime fechaGeneracion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string indLugarFisico;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string idEnvio;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public System.DateTime fechaDespacho;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public int cantFojas;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string nroReferencia;
        
        public AvisoRecepAceptRequestBody() {
        }
        
        public AvisoRecepAceptRequestBody(
                    InvocacionServWDigDepFiel.wDigDepFiel.Autenticacion autentica, 
                    string nroLegajo, 
                    string cuitDeclarante, 
                    string cuitPSAD, 
                    string cuitIE, 
                    string codigo, 
                    System.DateTime fechaHoraAcept, 
                    string ticket, 
                    string sigea, 
                    string nroGuia, 
                    System.DateTime fechaGeneracion, 
                    string indLugarFisico, 
                    string idEnvio, 
                    System.DateTime fechaDespacho, 
                    int cantFojas, 
                    string nroReferencia) {
            this.autentica = autentica;
            this.nroLegajo = nroLegajo;
            this.cuitDeclarante = cuitDeclarante;
            this.cuitPSAD = cuitPSAD;
            this.cuitIE = cuitIE;
            this.codigo = codigo;
            this.fechaHoraAcept = fechaHoraAcept;
            this.ticket = ticket;
            this.sigea = sigea;
            this.nroGuia = nroGuia;
            this.fechaGeneracion = fechaGeneracion;
            this.indLugarFisico = indLugarFisico;
            this.idEnvio = idEnvio;
            this.fechaDespacho = fechaDespacho;
            this.cantFojas = cantFojas;
            this.nroReferencia = nroReferencia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AvisoRecepAceptResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AvisoRecepAceptResponse", Namespace="ar.gov.afip.dia.serviciosWeb.wDigDepFiel", Order=0)]
        public InvocacionServWDigDepFiel.wDigDepFiel.AvisoRecepAceptResponseBody Body;
        
        public AvisoRecepAceptResponse() {
        }
        
        public AvisoRecepAceptResponse(InvocacionServWDigDepFiel.wDigDepFiel.AvisoRecepAceptResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="ar.gov.afip.dia.serviciosWeb.wDigDepFiel")]
    public partial class AvisoRecepAceptResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public InvocacionServWDigDepFiel.wDigDepFiel.Recibo AvisoRecepAceptResult;
        
        public AvisoRecepAceptResponseBody() {
        }
        
        public AvisoRecepAceptResponseBody(InvocacionServWDigDepFiel.wDigDepFiel.Recibo AvisoRecepAceptResult) {
            this.AvisoRecepAceptResult = AvisoRecepAceptResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AvisoDigitRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AvisoDigit", Namespace="ar.gov.afip.dia.serviciosWeb.wDigDepFiel", Order=0)]
        public InvocacionServWDigDepFiel.wDigDepFiel.AvisoDigitRequestBody Body;
        
        public AvisoDigitRequest() {
        }
        
        public AvisoDigitRequest(InvocacionServWDigDepFiel.wDigDepFiel.AvisoDigitRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="ar.gov.afip.dia.serviciosWeb.wDigDepFiel")]
    public partial class AvisoDigitRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public InvocacionServWDigDepFiel.wDigDepFiel.Autenticacion autentica;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nroLegajo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cuitDeclarante;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string cuitPSAD;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string cuitIE;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string cuitATA;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string codigo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string url;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public InvocacionServWDigDepFiel.wDigDepFiel.Familia[] familias;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string ticket;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string hashing;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public int cantidadTotal;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string sigea;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string nroReferencia;
        
        public AvisoDigitRequestBody() {
        }
        
        public AvisoDigitRequestBody(InvocacionServWDigDepFiel.wDigDepFiel.Autenticacion autentica, string nroLegajo, string cuitDeclarante, string cuitPSAD, string cuitIE, string cuitATA, string codigo, string url, InvocacionServWDigDepFiel.wDigDepFiel.Familia[] familias, string ticket, string hashing, int cantidadTotal, string sigea, string nroReferencia) {
            this.autentica = autentica;
            this.nroLegajo = nroLegajo;
            this.cuitDeclarante = cuitDeclarante;
            this.cuitPSAD = cuitPSAD;
            this.cuitIE = cuitIE;
            this.cuitATA = cuitATA;
            this.codigo = codigo;
            this.url = url;
            this.familias = familias;
            this.ticket = ticket;
            this.hashing = hashing;
            this.cantidadTotal = cantidadTotal;
            this.sigea = sigea;
            this.nroReferencia = nroReferencia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AvisoDigitResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AvisoDigitResponse", Namespace="ar.gov.afip.dia.serviciosWeb.wDigDepFiel", Order=0)]
        public InvocacionServWDigDepFiel.wDigDepFiel.AvisoDigitResponseBody Body;
        
        public AvisoDigitResponse() {
        }
        
        public AvisoDigitResponse(InvocacionServWDigDepFiel.wDigDepFiel.AvisoDigitResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="ar.gov.afip.dia.serviciosWeb.wDigDepFiel")]
    public partial class AvisoDigitResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public InvocacionServWDigDepFiel.wDigDepFiel.Recibo AvisoDigitResult;
        
        public AvisoDigitResponseBody() {
        }
        
        public AvisoDigitResponseBody(InvocacionServWDigDepFiel.wDigDepFiel.Recibo AvisoDigitResult) {
            this.AvisoDigitResult = AvisoDigitResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DummyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Dummy", Namespace="ar.gov.afip.dia.serviciosWeb.wDigDepFiel", Order=0)]
        public InvocacionServWDigDepFiel.wDigDepFiel.DummyRequestBody Body;
        
        public DummyRequest() {
        }
        
        public DummyRequest(InvocacionServWDigDepFiel.wDigDepFiel.DummyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DummyRequestBody {
        
        public DummyRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DummyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DummyResponse", Namespace="ar.gov.afip.dia.serviciosWeb.wDigDepFiel", Order=0)]
        public InvocacionServWDigDepFiel.wDigDepFiel.DummyResponseBody Body;
        
        public DummyResponse() {
        }
        
        public DummyResponse(InvocacionServWDigDepFiel.wDigDepFiel.DummyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="ar.gov.afip.dia.serviciosWeb.wDigDepFiel")]
    public partial class DummyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public InvocacionServWDigDepFiel.wDigDepFiel.WsDummyResponse DummyResult;
        
        public DummyResponseBody() {
        }
        
        public DummyResponseBody(InvocacionServWDigDepFiel.wDigDepFiel.WsDummyResponse DummyResult) {
            this.DummyResult = DummyResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wDigDepFielSoapChannel : InvocacionServWDigDepFiel.wDigDepFiel.wDigDepFielSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wDigDepFielSoapClient : System.ServiceModel.ClientBase<InvocacionServWDigDepFiel.wDigDepFiel.wDigDepFielSoap>, InvocacionServWDigDepFiel.wDigDepFiel.wDigDepFielSoap {
        
        public wDigDepFielSoapClient() {
        }
        
        public wDigDepFielSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wDigDepFielSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wDigDepFielSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wDigDepFielSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InvocacionServWDigDepFiel.wDigDepFiel.AvisoRecepAceptResponse InvocacionServWDigDepFiel.wDigDepFiel.wDigDepFielSoap.AvisoRecepAcept(InvocacionServWDigDepFiel.wDigDepFiel.AvisoRecepAceptRequest request) {
            return base.Channel.AvisoRecepAcept(request);
        }
        
        public InvocacionServWDigDepFiel.wDigDepFiel.Recibo AvisoRecepAcept(
                    InvocacionServWDigDepFiel.wDigDepFiel.Autenticacion autentica, 
                    string nroLegajo, 
                    string cuitDeclarante, 
                    string cuitPSAD, 
                    string cuitIE, 
                    string codigo, 
                    System.DateTime fechaHoraAcept, 
                    string ticket, 
                    string sigea, 
                    string nroGuia, 
                    System.DateTime fechaGeneracion, 
                    string indLugarFisico, 
                    string idEnvio, 
                    System.DateTime fechaDespacho, 
                    int cantFojas, 
                    string nroReferencia) {
            InvocacionServWDigDepFiel.wDigDepFiel.AvisoRecepAceptRequest inValue = new InvocacionServWDigDepFiel.wDigDepFiel.AvisoRecepAceptRequest();
            inValue.Body = new InvocacionServWDigDepFiel.wDigDepFiel.AvisoRecepAceptRequestBody();
            inValue.Body.autentica = autentica;
            inValue.Body.nroLegajo = nroLegajo;
            inValue.Body.cuitDeclarante = cuitDeclarante;
            inValue.Body.cuitPSAD = cuitPSAD;
            inValue.Body.cuitIE = cuitIE;
            inValue.Body.codigo = codigo;
            inValue.Body.fechaHoraAcept = fechaHoraAcept;
            inValue.Body.ticket = ticket;
            inValue.Body.sigea = sigea;
            inValue.Body.nroGuia = nroGuia;
            inValue.Body.fechaGeneracion = fechaGeneracion;
            inValue.Body.indLugarFisico = indLugarFisico;
            inValue.Body.idEnvio = idEnvio;
            inValue.Body.fechaDespacho = fechaDespacho;
            inValue.Body.cantFojas = cantFojas;
            inValue.Body.nroReferencia = nroReferencia;
            InvocacionServWDigDepFiel.wDigDepFiel.AvisoRecepAceptResponse retVal = ((InvocacionServWDigDepFiel.wDigDepFiel.wDigDepFielSoap)(this)).AvisoRecepAcept(inValue);
            return retVal.Body.AvisoRecepAceptResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InvocacionServWDigDepFiel.wDigDepFiel.AvisoRecepAceptResponse> InvocacionServWDigDepFiel.wDigDepFiel.wDigDepFielSoap.AvisoRecepAceptAsync(InvocacionServWDigDepFiel.wDigDepFiel.AvisoRecepAceptRequest request) {
            return base.Channel.AvisoRecepAceptAsync(request);
        }
        
        public System.Threading.Tasks.Task<InvocacionServWDigDepFiel.wDigDepFiel.AvisoRecepAceptResponse> AvisoRecepAceptAsync(
                    InvocacionServWDigDepFiel.wDigDepFiel.Autenticacion autentica, 
                    string nroLegajo, 
                    string cuitDeclarante, 
                    string cuitPSAD, 
                    string cuitIE, 
                    string codigo, 
                    System.DateTime fechaHoraAcept, 
                    string ticket, 
                    string sigea, 
                    string nroGuia, 
                    System.DateTime fechaGeneracion, 
                    string indLugarFisico, 
                    string idEnvio, 
                    System.DateTime fechaDespacho, 
                    int cantFojas, 
                    string nroReferencia) {
            InvocacionServWDigDepFiel.wDigDepFiel.AvisoRecepAceptRequest inValue = new InvocacionServWDigDepFiel.wDigDepFiel.AvisoRecepAceptRequest();
            inValue.Body = new InvocacionServWDigDepFiel.wDigDepFiel.AvisoRecepAceptRequestBody();
            inValue.Body.autentica = autentica;
            inValue.Body.nroLegajo = nroLegajo;
            inValue.Body.cuitDeclarante = cuitDeclarante;
            inValue.Body.cuitPSAD = cuitPSAD;
            inValue.Body.cuitIE = cuitIE;
            inValue.Body.codigo = codigo;
            inValue.Body.fechaHoraAcept = fechaHoraAcept;
            inValue.Body.ticket = ticket;
            inValue.Body.sigea = sigea;
            inValue.Body.nroGuia = nroGuia;
            inValue.Body.fechaGeneracion = fechaGeneracion;
            inValue.Body.indLugarFisico = indLugarFisico;
            inValue.Body.idEnvio = idEnvio;
            inValue.Body.fechaDespacho = fechaDespacho;
            inValue.Body.cantFojas = cantFojas;
            inValue.Body.nroReferencia = nroReferencia;
            return ((InvocacionServWDigDepFiel.wDigDepFiel.wDigDepFielSoap)(this)).AvisoRecepAceptAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InvocacionServWDigDepFiel.wDigDepFiel.AvisoDigitResponse InvocacionServWDigDepFiel.wDigDepFiel.wDigDepFielSoap.AvisoDigit(InvocacionServWDigDepFiel.wDigDepFiel.AvisoDigitRequest request) {
            return base.Channel.AvisoDigit(request);
        }
        
        public InvocacionServWDigDepFiel.wDigDepFiel.Recibo AvisoDigit(InvocacionServWDigDepFiel.wDigDepFiel.Autenticacion autentica, string nroLegajo, string cuitDeclarante, string cuitPSAD, string cuitIE, string cuitATA, string codigo, string url, InvocacionServWDigDepFiel.wDigDepFiel.Familia[] familias, string ticket, string hashing, int cantidadTotal, string sigea, string nroReferencia) {
            InvocacionServWDigDepFiel.wDigDepFiel.AvisoDigitRequest inValue = new InvocacionServWDigDepFiel.wDigDepFiel.AvisoDigitRequest();
            inValue.Body = new InvocacionServWDigDepFiel.wDigDepFiel.AvisoDigitRequestBody();
            inValue.Body.autentica = autentica;
            inValue.Body.nroLegajo = nroLegajo;
            inValue.Body.cuitDeclarante = cuitDeclarante;
            inValue.Body.cuitPSAD = cuitPSAD;
            inValue.Body.cuitIE = cuitIE;
            inValue.Body.cuitATA = cuitATA;
            inValue.Body.codigo = codigo;
            inValue.Body.url = url;
            inValue.Body.familias = familias;
            inValue.Body.ticket = ticket;
            inValue.Body.hashing = hashing;
            inValue.Body.cantidadTotal = cantidadTotal;
            inValue.Body.sigea = sigea;
            inValue.Body.nroReferencia = nroReferencia;
            InvocacionServWDigDepFiel.wDigDepFiel.AvisoDigitResponse retVal = ((InvocacionServWDigDepFiel.wDigDepFiel.wDigDepFielSoap)(this)).AvisoDigit(inValue);
            return retVal.Body.AvisoDigitResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InvocacionServWDigDepFiel.wDigDepFiel.AvisoDigitResponse> InvocacionServWDigDepFiel.wDigDepFiel.wDigDepFielSoap.AvisoDigitAsync(InvocacionServWDigDepFiel.wDigDepFiel.AvisoDigitRequest request) {
            return base.Channel.AvisoDigitAsync(request);
        }
        
        public System.Threading.Tasks.Task<InvocacionServWDigDepFiel.wDigDepFiel.AvisoDigitResponse> AvisoDigitAsync(InvocacionServWDigDepFiel.wDigDepFiel.Autenticacion autentica, string nroLegajo, string cuitDeclarante, string cuitPSAD, string cuitIE, string cuitATA, string codigo, string url, InvocacionServWDigDepFiel.wDigDepFiel.Familia[] familias, string ticket, string hashing, int cantidadTotal, string sigea, string nroReferencia) {
            InvocacionServWDigDepFiel.wDigDepFiel.AvisoDigitRequest inValue = new InvocacionServWDigDepFiel.wDigDepFiel.AvisoDigitRequest();
            inValue.Body = new InvocacionServWDigDepFiel.wDigDepFiel.AvisoDigitRequestBody();
            inValue.Body.autentica = autentica;
            inValue.Body.nroLegajo = nroLegajo;
            inValue.Body.cuitDeclarante = cuitDeclarante;
            inValue.Body.cuitPSAD = cuitPSAD;
            inValue.Body.cuitIE = cuitIE;
            inValue.Body.cuitATA = cuitATA;
            inValue.Body.codigo = codigo;
            inValue.Body.url = url;
            inValue.Body.familias = familias;
            inValue.Body.ticket = ticket;
            inValue.Body.hashing = hashing;
            inValue.Body.cantidadTotal = cantidadTotal;
            inValue.Body.sigea = sigea;
            inValue.Body.nroReferencia = nroReferencia;
            return ((InvocacionServWDigDepFiel.wDigDepFiel.wDigDepFielSoap)(this)).AvisoDigitAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InvocacionServWDigDepFiel.wDigDepFiel.DummyResponse InvocacionServWDigDepFiel.wDigDepFiel.wDigDepFielSoap.Dummy(InvocacionServWDigDepFiel.wDigDepFiel.DummyRequest request) {
            return base.Channel.Dummy(request);
        }
        
        public InvocacionServWDigDepFiel.wDigDepFiel.WsDummyResponse Dummy() {
            InvocacionServWDigDepFiel.wDigDepFiel.DummyRequest inValue = new InvocacionServWDigDepFiel.wDigDepFiel.DummyRequest();
            inValue.Body = new InvocacionServWDigDepFiel.wDigDepFiel.DummyRequestBody();
            InvocacionServWDigDepFiel.wDigDepFiel.DummyResponse retVal = ((InvocacionServWDigDepFiel.wDigDepFiel.wDigDepFielSoap)(this)).Dummy(inValue);
            return retVal.Body.DummyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InvocacionServWDigDepFiel.wDigDepFiel.DummyResponse> InvocacionServWDigDepFiel.wDigDepFiel.wDigDepFielSoap.DummyAsync(InvocacionServWDigDepFiel.wDigDepFiel.DummyRequest request) {
            return base.Channel.DummyAsync(request);
        }
        
        public System.Threading.Tasks.Task<InvocacionServWDigDepFiel.wDigDepFiel.DummyResponse> DummyAsync() {
            InvocacionServWDigDepFiel.wDigDepFiel.DummyRequest inValue = new InvocacionServWDigDepFiel.wDigDepFiel.DummyRequest();
            inValue.Body = new InvocacionServWDigDepFiel.wDigDepFiel.DummyRequestBody();
            return ((InvocacionServWDigDepFiel.wDigDepFiel.wDigDepFielSoap)(this)).DummyAsync(inValue);
        }
    }
}
